alter table incidents
  add column version bigint not null default 0;

create table audit_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamp with time zone not null,
  actor varchar(120) not null,
  action varchar(80) not null,
  target_type varchar(80) not null,
  target_id varchar(80) not null,
  outcome varchar(40) not null,
  message varchar(1000) not null,
  constraint audit_events_outcome_check check (outcome in ('SUCCESS', 'REJECTED', 'FAILED'))
);

create index idx_audit_events_target on audit_events(target_type, target_id);
create index idx_audit_events_occurred_at on audit_events(occurred_at);

