-- Refresh tokens are stored as SHA-256 hashes so rotation and reuse detection
-- can be enforced server-side without keeping raw tokens in the database.
create table refresh_tokens (
  id bigint generated by default as identity primary key,
  subject varchar(120) not null,
  token_hash varchar(64) not null,
  issued_at timestamp with time zone not null,
  expires_at timestamp with time zone not null,
  replaced_by varchar(64),
  revoked_at timestamp with time zone
);

create unique index uq_refresh_tokens_token_hash on refresh_tokens(token_hash);
create index idx_refresh_tokens_subject on refresh_tokens(subject);
