spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/infraflow
    username: infraflow
    password: infraflow
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: info
